version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=medin
      - POSTGRES_DB=medin
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      # - 7001:7001
  store-front:
    build:
      context: ./medin-storefront
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - app
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  postgres-db:
  cache:
